module.exports.capitalize = require('./lib/capitalize')
module.exports.randomizeArray = require('./lib/Randomize')
module.exports.randomizeNumber = require('./lib/Randomize')
module.exports.passwdGen = require('./lib/Password')
module.exports.FindObject = require('./lib/FindObject')
